### ISSUE TITLE
Can't save new CMS block

### ISSUE THREAD

**Issue by ljudalj-orot** [mage2pro/markdown#4]
When Markdown extension is enabled - can't save new cms block.
Save buttons just don't work without any messages in console.
In the same time - form validation works ok, and existing blocks can be edited and saved without problems.
Magento version 2.3.1
Screencast of the issue: https://monosnap.com/file/slGRdlIbm7ToGcxLMWDU1iOVxUYiUE

**Comment by dmitrii-fediuk** [comment]
[Buy the module's license](https://mage2.pro/t/160) first to get support for the module.
